apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: erp
  template:
    metadata:
      labels:
        app: erp
    spec:
      containers:
      - name: erp
        image: erp:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 5260
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5260"
