FROM mcr.microsoft.com/dotnet/aspnet:9.0-nanoserver-1809 AS base
WORKDIR /app
EXPOSE 5260

ENV ASPNETCORE_URLS=http://+:5260

FROM mcr.microsoft.com/dotnet/sdk:9.0-nanoserver-1809 AS build
ARG configuration=Release
WORKDIR /src
COPY ["ERP/ERP/ERP.csproj", "ERP/ERP/"]
RUN dotnet restore "ERP\ERP\ERP.csproj"
COPY . .
WORKDIR "/src/ERP/ERP"
RUN dotnet build "ERP.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "ERP.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ERP.dll"]
