name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb_ci
          PGUSER: testuser
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ConnectionStrings__PostgresTestDb: Host=localhost;Port=5432;Username=testuser;Password=testpass;Database=testdb_ci

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Setup PostgreSQL
      run: |
        chmod +x ERP/ERP/ERP/setup_postgres.sh
          .ERP/ERP/ERP/setup_postgres.sh

    
    - name: Setup PostgreSQL User
      run: |
        export PGPASSWORD=testpass
        psql -h localhost -U testuser -c "CREATE ROLE testuser WITH LOGIN PASSWORD 'testpass';"
        psql -h localhost -U testuser -c "CREATE DATABASE testdb_ci WITH OWNER testuser;"